# Generated by Django 4.2.5 on 2023-10-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_rename_number_of_beds_apartment_number_of_bedrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='size_of_balcony',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Balcony Size (in sqm)'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='size_of_bedrooms',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Bedroom Size (in sqm)'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='size_of_kitchen',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
