# Generated by Django 4.2.5 on 2023-10-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_apartment_size_of_balcony_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='maximix_number_of_guests',
            new_name='maximum_number_of_guests',
        ),
    ]
