# Generated by Django 4.2.5 on 2023-10-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number_of_guests',
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_adults',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_kids',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
